name: Auto Advice Logger
permissions:
  contents: write    
on:
  schedule:
    - cron: "0 * * * *"   # Every hour
  workflow_dispatch:

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y curl jq git

      - name: Fetch advice and commit
        run: |
          DATETIME=$(date +"%Y-%m-%d %H:%M:%S")
          ADVICE=$(curl -s https://api.adviceslip.com/advice | jq -r '.slip.advice')
          echo "$DATETIME | $ADVICE" >> cristian.rosario.advices
          git config user.name "Crosario12005"
          git config user.email "rosario12005@gmail.com"
          git add cristian.rosario.advices
          git commit -m "Auto update: $DATETIME" || echo "No changes to commit"
          git push

